apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: k8s-pod-watcher
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN: {{ .Values.telegram.token | quote }}
  TELEGRAM_CHAT_ID: {{ .Values.telegram.chatID | quote }}
  DISCORD_WEBHOOK: {{ .Values.discord.webHook | quote }}
  SLACK_WEBHOOK: {{ .Values.slack.webHook | quote }}