# =======================
# APP SETTINGS
# =======================

appLabel: pod-watcher-operator

image:
  repository: ghcr.io/zapi-web/k8s-pod-watcher
  tag: latest
  pullPolicy: IfNotPresent

logLevel: info

metrics:
  enabled: false
  port: 8080
  path: /metrics

channels: telegram # for example: telegram,discord,slack (separated by ',')

# =======================
# SECRETS
# =======================

telegram:
  token: ""
  chatID: ""
discord:
  webHook: ""
slack:
  webHook: ""

# =======================
# RESOURCES
# =======================

resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 20m
    memory: 32Mi