apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-operator
  namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Namespace }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.appLabel }}
    spec:
      serviceAccountName: {{ .Release.Name }}-operator
      containers:
      - name: watcher
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}

        env:
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: TELEGRAM_BOT_TOKEN
        - name: TELEGRAM_CHAT_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: TELEGRAM_CHAT_ID
        - name: LOG_LEVEL
          value: {{ .Values.logLevel | quote }}

        ports:
        - containerPort: 8080
          name: metrics

        resources:
          {{- toYaml .Values.resources | nindent 10}}
        
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65532 
