apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN: {{ .Values.telegram.token | quote }}
  TELEGRAM_CHAT_ID: {{ .Values.telegram.chatID | quote }}