name: Main Pipeline

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    go-tests:
        uses: ./.github/workflows/go.yaml
    
    docker-registry-push:
        uses: ./.github/workflows/docker.yaml
        needs: go-tests
        if: github.event_name == 'push'
        secrets: inherit
        permissions:
            contents: read
            packages: write

    helm-registry-push:
        uses: ./.github/workflows/helm.yaml
        needs: go-tests
        if: github.event_name == 'push'
        secrets: inherit
        permissions:
            contents: read
            packages: write